package com.google.android.gms.internal.mlkit_common;

import lm.b;
import lm.c;
import lm.d;

/* loaded from: classes3.dex */
final class zzfd implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzfd zza = new zzfd();
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzb;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C0705b a11 = b.a("systemInfo");
        zzbh zzbhVar = new zzbh();
        zzbhVar.zza(1);
        zzb = a11.b(zzbhVar.zzb()).a();
        b.C0705b a12 = b.a("eventName");
        zzbh zzbhVar2 = new zzbh();
        zzbhVar2.zza(2);
        zzc = a12.b(zzbhVar2.zzb()).a();
        b.C0705b a13 = b.a("isThickClient");
        zzbh zzbhVar3 = new zzbh();
        zzbhVar3.zza(37);
        zzd = a13.b(zzbhVar3.zzb()).a();
        b.C0705b a14 = b.a("clientType");
        zzbh zzbhVar4 = new zzbh();
        zzbhVar4.zza(61);
        zze = a14.b(zzbhVar4.zzb()).a();
        b.C0705b a15 = b.a("modelDownloadLogEvent");
        zzbh zzbhVar5 = new zzbh();
        zzbhVar5.zza(3);
        zzf = a15.b(zzbhVar5.zzb()).a();
        b.C0705b a16 = b.a("customModelLoadLogEvent");
        zzbh zzbhVar6 = new zzbh();
        zzbhVar6.zza(20);
        zzg = a16.b(zzbhVar6.zzb()).a();
        b.C0705b a17 = b.a("customModelInferenceLogEvent");
        zzbh zzbhVar7 = new zzbh();
        zzbhVar7.zza(4);
        zzh = a17.b(zzbhVar7.zzb()).a();
        b.C0705b a18 = b.a("customModelCreateLogEvent");
        zzbh zzbhVar8 = new zzbh();
        zzbhVar8.zza(29);
        zzi = a18.b(zzbhVar8.zzb()).a();
        b.C0705b a19 = b.a("onDeviceFaceDetectionLogEvent");
        zzbh zzbhVar9 = new zzbh();
        zzbhVar9.zza(5);
        zzj = a19.b(zzbhVar9.zzb()).a();
        b.C0705b a21 = b.a("onDeviceFaceLoadLogEvent");
        zzbh zzbhVar10 = new zzbh();
        zzbhVar10.zza(59);
        zzk = a21.b(zzbhVar10.zzb()).a();
        b.C0705b a22 = b.a("onDeviceTextDetectionLogEvent");
        zzbh zzbhVar11 = new zzbh();
        zzbhVar11.zza(6);
        zzl = a22.b(zzbhVar11.zzb()).a();
        b.C0705b a23 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzbh zzbhVar12 = new zzbh();
        zzbhVar12.zza(79);
        zzm = a23.b(zzbhVar12.zzb()).a();
        b.C0705b a24 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzbh zzbhVar13 = new zzbh();
        zzbhVar13.zza(7);
        zzn = a24.b(zzbhVar13.zzb()).a();
        b.C0705b a25 = b.a("onDeviceBarcodeLoadLogEvent");
        zzbh zzbhVar14 = new zzbh();
        zzbhVar14.zza(58);
        zzo = a25.b(zzbhVar14.zzb()).a();
        b.C0705b a26 = b.a("onDeviceImageLabelCreateLogEvent");
        zzbh zzbhVar15 = new zzbh();
        zzbhVar15.zza(48);
        zzp = a26.b(zzbhVar15.zzb()).a();
        b.C0705b a27 = b.a("onDeviceImageLabelLoadLogEvent");
        zzbh zzbhVar16 = new zzbh();
        zzbhVar16.zza(49);
        zzq = a27.b(zzbhVar16.zzb()).a();
        b.C0705b a28 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzbh zzbhVar17 = new zzbh();
        zzbhVar17.zza(18);
        zzr = a28.b(zzbhVar17.zzb()).a();
        b.C0705b a29 = b.a("onDeviceObjectCreateLogEvent");
        zzbh zzbhVar18 = new zzbh();
        zzbhVar18.zza(26);
        zzs = a29.b(zzbhVar18.zzb()).a();
        b.C0705b a31 = b.a("onDeviceObjectLoadLogEvent");
        zzbh zzbhVar19 = new zzbh();
        zzbhVar19.zza(27);
        zzt = a31.b(zzbhVar19.zzb()).a();
        b.C0705b a32 = b.a("onDeviceObjectInferenceLogEvent");
        zzbh zzbhVar20 = new zzbh();
        zzbhVar20.zza(28);
        zzu = a32.b(zzbhVar20.zzb()).a();
        b.C0705b a33 = b.a("onDevicePoseDetectionLogEvent");
        zzbh zzbhVar21 = new zzbh();
        zzbhVar21.zza(44);
        zzv = a33.b(zzbhVar21.zzb()).a();
        b.C0705b a34 = b.a("onDeviceSegmentationLogEvent");
        zzbh zzbhVar22 = new zzbh();
        zzbhVar22.zza(45);
        zzw = a34.b(zzbhVar22.zzb()).a();
        b.C0705b a35 = b.a("onDeviceSmartReplyLogEvent");
        zzbh zzbhVar23 = new zzbh();
        zzbhVar23.zza(19);
        zzx = a35.b(zzbhVar23.zzb()).a();
        b.C0705b a36 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzbh zzbhVar24 = new zzbh();
        zzbhVar24.zza(21);
        zzy = a36.b(zzbhVar24.zzb()).a();
        b.C0705b a37 = b.a("onDeviceTranslationLogEvent");
        zzbh zzbhVar25 = new zzbh();
        zzbhVar25.zza(22);
        zzz = a37.b(zzbhVar25.zzb()).a();
        b.C0705b a38 = b.a("cloudFaceDetectionLogEvent");
        zzbh zzbhVar26 = new zzbh();
        zzbhVar26.zza(8);
        zzA = a38.b(zzbhVar26.zzb()).a();
        b.C0705b a39 = b.a("cloudCropHintDetectionLogEvent");
        zzbh zzbhVar27 = new zzbh();
        zzbhVar27.zza(9);
        zzB = a39.b(zzbhVar27.zzb()).a();
        b.C0705b a41 = b.a("cloudDocumentTextDetectionLogEvent");
        zzbh zzbhVar28 = new zzbh();
        zzbhVar28.zza(10);
        zzC = a41.b(zzbhVar28.zzb()).a();
        b.C0705b a42 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzbh zzbhVar29 = new zzbh();
        zzbhVar29.zza(11);
        zzD = a42.b(zzbhVar29.zzb()).a();
        b.C0705b a43 = b.a("cloudImageLabelDetectionLogEvent");
        zzbh zzbhVar30 = new zzbh();
        zzbhVar30.zza(12);
        zzE = a43.b(zzbhVar30.zzb()).a();
        b.C0705b a44 = b.a("cloudLandmarkDetectionLogEvent");
        zzbh zzbhVar31 = new zzbh();
        zzbhVar31.zza(13);
        zzF = a44.b(zzbhVar31.zzb()).a();
        b.C0705b a45 = b.a("cloudLogoDetectionLogEvent");
        zzbh zzbhVar32 = new zzbh();
        zzbhVar32.zza(14);
        zzG = a45.b(zzbhVar32.zzb()).a();
        b.C0705b a46 = b.a("cloudSafeSearchDetectionLogEvent");
        zzbh zzbhVar33 = new zzbh();
        zzbhVar33.zza(15);
        zzH = a46.b(zzbhVar33.zzb()).a();
        b.C0705b a47 = b.a("cloudTextDetectionLogEvent");
        zzbh zzbhVar34 = new zzbh();
        zzbhVar34.zza(16);
        zzI = a47.b(zzbhVar34.zzb()).a();
        b.C0705b a48 = b.a("cloudWebSearchDetectionLogEvent");
        zzbh zzbhVar35 = new zzbh();
        zzbhVar35.zza(17);
        zzJ = a48.b(zzbhVar35.zzb()).a();
        b.C0705b a49 = b.a("automlImageLabelingCreateLogEvent");
        zzbh zzbhVar36 = new zzbh();
        zzbhVar36.zza(23);
        zzK = a49.b(zzbhVar36.zzb()).a();
        b.C0705b a51 = b.a("automlImageLabelingLoadLogEvent");
        zzbh zzbhVar37 = new zzbh();
        zzbhVar37.zza(24);
        zzL = a51.b(zzbhVar37.zzb()).a();
        b.C0705b a52 = b.a("automlImageLabelingInferenceLogEvent");
        zzbh zzbhVar38 = new zzbh();
        zzbhVar38.zza(25);
        zzM = a52.b(zzbhVar38.zzb()).a();
        b.C0705b a53 = b.a("isModelDownloadedLogEvent");
        zzbh zzbhVar39 = new zzbh();
        zzbhVar39.zza(39);
        zzN = a53.b(zzbhVar39.zzb()).a();
        b.C0705b a54 = b.a("deleteModelLogEvent");
        zzbh zzbhVar40 = new zzbh();
        zzbhVar40.zza(40);
        zzO = a54.b(zzbhVar40.zzb()).a();
        b.C0705b a55 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzbh zzbhVar41 = new zzbh();
        zzbhVar41.zza(30);
        zzP = a55.b(zzbhVar41.zzb()).a();
        b.C0705b a56 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzbh zzbhVar42 = new zzbh();
        zzbhVar42.zza(31);
        zzQ = a56.b(zzbhVar42.zzb()).a();
        b.C0705b a57 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzbh zzbhVar43 = new zzbh();
        zzbhVar43.zza(32);
        zzR = a57.b(zzbhVar43.zzb()).a();
        b.C0705b a58 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzbh zzbhVar44 = new zzbh();
        zzbhVar44.zza(33);
        zzS = a58.b(zzbhVar44.zzb()).a();
        b.C0705b a59 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzbh zzbhVar45 = new zzbh();
        zzbhVar45.zza(34);
        zzT = a59.b(zzbhVar45.zzb()).a();
        b.C0705b a61 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzbh zzbhVar46 = new zzbh();
        zzbhVar46.zza(35);
        zzU = a61.b(zzbhVar46.zzb()).a();
        b.C0705b a62 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzbh zzbhVar47 = new zzbh();
        zzbhVar47.zza(36);
        zzV = a62.b(zzbhVar47.zzb()).a();
        b.C0705b a63 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzbh zzbhVar48 = new zzbh();
        zzbhVar48.zza(46);
        zzW = a63.b(zzbhVar48.zzb()).a();
        b.C0705b a64 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzbh zzbhVar49 = new zzbh();
        zzbhVar49.zza(47);
        zzX = a64.b(zzbhVar49.zzb()).a();
        b.C0705b a65 = b.a("pipelineAccelerationInferenceEvents");
        zzbh zzbhVar50 = new zzbh();
        zzbhVar50.zza(69);
        zzY = a65.b(zzbhVar50.zzb()).a();
        b.C0705b a66 = b.a("remoteConfigLogEvent");
        zzbh zzbhVar51 = new zzbh();
        zzbhVar51.zza(42);
        zzZ = a66.b(zzbhVar51.zzb()).a();
        b.C0705b a67 = b.a("inputImageConstructionLogEvent");
        zzbh zzbhVar52 = new zzbh();
        zzbhVar52.zza(50);
        zzaa = a67.b(zzbhVar52.zzb()).a();
        b.C0705b a68 = b.a("leakedHandleEvent");
        zzbh zzbhVar53 = new zzbh();
        zzbhVar53.zza(51);
        zzab = a68.b(zzbhVar53.zzb()).a();
        b.C0705b a69 = b.a("cameraSourceLogEvent");
        zzbh zzbhVar54 = new zzbh();
        zzbhVar54.zza(52);
        zzac = a69.b(zzbhVar54.zzb()).a();
        b.C0705b a71 = b.a("imageLabelOptionalModuleLogEvent");
        zzbh zzbhVar55 = new zzbh();
        zzbhVar55.zza(53);
        zzad = a71.b(zzbhVar55.zzb()).a();
        b.C0705b a72 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzbh zzbhVar56 = new zzbh();
        zzbhVar56.zza(54);
        zzae = a72.b(zzbhVar56.zzb()).a();
        b.C0705b a73 = b.a("faceDetectionOptionalModuleLogEvent");
        zzbh zzbhVar57 = new zzbh();
        zzbhVar57.zza(60);
        zzaf = a73.b(zzbhVar57.zzb()).a();
        b.C0705b a74 = b.a("nlClassifierOptionalModuleLogEvent");
        zzbh zzbhVar58 = new zzbh();
        zzbhVar58.zza(55);
        zzag = a74.b(zzbhVar58.zzb()).a();
        b.C0705b a75 = b.a("nlClassifierClientLibraryLogEvent");
        zzbh zzbhVar59 = new zzbh();
        zzbhVar59.zza(56);
        zzah = a75.b(zzbhVar59.zzb()).a();
        b.C0705b a76 = b.a("accelerationAllowlistLogEvent");
        zzbh zzbhVar60 = new zzbh();
        zzbhVar60.zza(57);
        zzai = a76.b(zzbhVar60.zzb()).a();
        b.C0705b a77 = b.a("toxicityDetectionCreateEvent");
        zzbh zzbhVar61 = new zzbh();
        zzbhVar61.zza(62);
        zzaj = a77.b(zzbhVar61.zzb()).a();
        b.C0705b a78 = b.a("toxicityDetectionLoadEvent");
        zzbh zzbhVar62 = new zzbh();
        zzbhVar62.zza(63);
        zzak = a78.b(zzbhVar62.zzb()).a();
        b.C0705b a79 = b.a("toxicityDetectionInferenceEvent");
        zzbh zzbhVar63 = new zzbh();
        zzbhVar63.zza(64);
        zzal = a79.b(zzbhVar63.zzb()).a();
        b.C0705b a81 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzbh zzbhVar64 = new zzbh();
        zzbhVar64.zza(65);
        zzam = a81.b(zzbhVar64.zzb()).a();
        b.C0705b a82 = b.a("customImageLabelOptionalModuleLogEvent");
        zzbh zzbhVar65 = new zzbh();
        zzbhVar65.zza(66);
        zzan = a82.b(zzbhVar65.zzb()).a();
        b.C0705b a83 = b.a("codeScannerScanApiEvent");
        zzbh zzbhVar66 = new zzbh();
        zzbhVar66.zza(67);
        zzao = a83.b(zzbhVar66.zzb()).a();
        b.C0705b a84 = b.a("codeScannerOptionalModuleEvent");
        zzbh zzbhVar67 = new zzbh();
        zzbhVar67.zza(68);
        zzap = a84.b(zzbhVar67.zzb()).a();
        b.C0705b a85 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzbh zzbhVar68 = new zzbh();
        zzbhVar68.zza(70);
        zzaq = a85.b(zzbhVar68.zzb()).a();
        b.C0705b a86 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzbh zzbhVar69 = new zzbh();
        zzbhVar69.zza(71);
        zzar = a86.b(zzbhVar69.zzb()).a();
        b.C0705b a87 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzbh zzbhVar70 = new zzbh();
        zzbhVar70.zza(72);
        zzas = a87.b(zzbhVar70.zzb()).a();
        b.C0705b a88 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzbh zzbhVar71 = new zzbh();
        zzbhVar71.zza(73);
        zzat = a88.b(zzbhVar71.zzb()).a();
        b.C0705b a89 = b.a("onDeviceSelfieFaceCreateLogEvent");
        zzbh zzbhVar72 = new zzbh();
        zzbhVar72.zza(74);
        zzau = a89.b(zzbhVar72.zzb()).a();
        b.C0705b a90 = b.a("onDeviceSelfieFaceLoadLogEvent");
        zzbh zzbhVar73 = new zzbh();
        zzbhVar73.zza(75);
        zzav = a90.b(zzbhVar73.zzb()).a();
        b.C0705b a91 = b.a("onDeviceSelfieFaceLogEvent");
        zzbh zzbhVar74 = new zzbh();
        zzbhVar74.zza(76);
        zzaw = a91.b(zzbhVar74.zzb()).a();
        b.C0705b a92 = b.a("aggregatedOnDeviceSelfieFaceLogEvent");
        zzbh zzbhVar75 = new zzbh();
        zzbhVar75.zza(77);
        zzax = a92.b(zzbhVar75.zzb()).a();
        b.C0705b a93 = b.a("smartReplyOptionalModuleLogEvent");
        zzbh zzbhVar76 = new zzbh();
        zzbhVar76.zza(78);
        zzay = a93.b(zzbhVar76.zzb()).a();
    }

    private zzfd() {
    }

    @Override // lm.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzjc zzjcVar = (zzjc) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zzjcVar.zzf());
        dVar.add(zzc, zzjcVar.zzd());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) null);
        dVar.add(zzf, zzjcVar.zze());
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, zzjcVar.zzb());
        dVar.add(zzO, zzjcVar.zza());
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, (Object) null);
        dVar.add(zzab, zzjcVar.zzc());
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
    }
}