package b30;

import kotlin.jvm.internal.s;
import vz.o;

/* loaded from: classes5.dex */
public interface a<T> {

    /* renamed from: b30.a$a  reason: collision with other inner class name */
    /* loaded from: classes5.dex */
    public static final class C0144a {
        public static <T> T[] a(a<T> aVar, int i11) {
            s.g(aVar, "this");
            throw new o("Generated by Android Extensions automatically");
        }
    }
}