package com.google.android.gms.internal.mlkit_vision_common;

import lm.b;
import lm.c;
import lm.d;

/* loaded from: classes3.dex */
final class zzea implements c {
    private static final b zzA;
    private static final b zzB;
    private static final b zzC;
    private static final b zzD;
    private static final b zzE;
    private static final b zzF;
    private static final b zzG;
    private static final b zzH;
    private static final b zzI;
    private static final b zzJ;
    private static final b zzK;
    private static final b zzL;
    private static final b zzM;
    private static final b zzN;
    private static final b zzO;
    private static final b zzP;
    private static final b zzQ;
    private static final b zzR;
    private static final b zzS;
    private static final b zzT;
    private static final b zzU;
    private static final b zzV;
    private static final b zzW;
    private static final b zzX;
    private static final b zzY;
    private static final b zzZ;
    static final zzea zza = new zzea();
    private static final b zzaa;
    private static final b zzab;
    private static final b zzac;
    private static final b zzad;
    private static final b zzae;
    private static final b zzaf;
    private static final b zzag;
    private static final b zzah;
    private static final b zzai;
    private static final b zzaj;
    private static final b zzak;
    private static final b zzal;
    private static final b zzam;
    private static final b zzan;
    private static final b zzao;
    private static final b zzap;
    private static final b zzaq;
    private static final b zzar;
    private static final b zzas;
    private static final b zzat;
    private static final b zzau;
    private static final b zzav;
    private static final b zzaw;
    private static final b zzax;
    private static final b zzay;
    private static final b zzaz;
    private static final b zzb;
    private static final b zzc;
    private static final b zzd;
    private static final b zze;
    private static final b zzf;
    private static final b zzg;
    private static final b zzh;
    private static final b zzi;
    private static final b zzj;
    private static final b zzk;
    private static final b zzl;
    private static final b zzm;
    private static final b zzn;
    private static final b zzo;
    private static final b zzp;
    private static final b zzq;
    private static final b zzr;
    private static final b zzs;
    private static final b zzt;
    private static final b zzu;
    private static final b zzv;
    private static final b zzw;
    private static final b zzx;
    private static final b zzy;
    private static final b zzz;

    static {
        b.C0705b a11 = b.a("systemInfo");
        zzae zzaeVar = new zzae();
        zzaeVar.zza(1);
        zzb = a11.b(zzaeVar.zzb()).a();
        b.C0705b a12 = b.a("eventName");
        zzae zzaeVar2 = new zzae();
        zzaeVar2.zza(2);
        zzc = a12.b(zzaeVar2.zzb()).a();
        b.C0705b a13 = b.a("isThickClient");
        zzae zzaeVar3 = new zzae();
        zzaeVar3.zza(37);
        zzd = a13.b(zzaeVar3.zzb()).a();
        b.C0705b a14 = b.a("clientType");
        zzae zzaeVar4 = new zzae();
        zzaeVar4.zza(61);
        zze = a14.b(zzaeVar4.zzb()).a();
        b.C0705b a15 = b.a("modelDownloadLogEvent");
        zzae zzaeVar5 = new zzae();
        zzaeVar5.zza(3);
        zzf = a15.b(zzaeVar5.zzb()).a();
        b.C0705b a16 = b.a("customModelLoadLogEvent");
        zzae zzaeVar6 = new zzae();
        zzaeVar6.zza(20);
        zzg = a16.b(zzaeVar6.zzb()).a();
        b.C0705b a17 = b.a("customModelInferenceLogEvent");
        zzae zzaeVar7 = new zzae();
        zzaeVar7.zza(4);
        zzh = a17.b(zzaeVar7.zzb()).a();
        b.C0705b a18 = b.a("customModelCreateLogEvent");
        zzae zzaeVar8 = new zzae();
        zzaeVar8.zza(29);
        zzi = a18.b(zzaeVar8.zzb()).a();
        b.C0705b a19 = b.a("onDeviceFaceDetectionLogEvent");
        zzae zzaeVar9 = new zzae();
        zzaeVar9.zza(5);
        zzj = a19.b(zzaeVar9.zzb()).a();
        b.C0705b a21 = b.a("onDeviceFaceLoadLogEvent");
        zzae zzaeVar10 = new zzae();
        zzaeVar10.zza(59);
        zzk = a21.b(zzaeVar10.zzb()).a();
        b.C0705b a22 = b.a("onDeviceTextDetectionLogEvent");
        zzae zzaeVar11 = new zzae();
        zzaeVar11.zza(6);
        zzl = a22.b(zzaeVar11.zzb()).a();
        b.C0705b a23 = b.a("onDeviceTextDetectionLoadLogEvent");
        zzae zzaeVar12 = new zzae();
        zzaeVar12.zza(79);
        zzm = a23.b(zzaeVar12.zzb()).a();
        b.C0705b a24 = b.a("onDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar13 = new zzae();
        zzaeVar13.zza(7);
        zzn = a24.b(zzaeVar13.zzb()).a();
        b.C0705b a25 = b.a("onDeviceBarcodeLoadLogEvent");
        zzae zzaeVar14 = new zzae();
        zzaeVar14.zza(58);
        zzo = a25.b(zzaeVar14.zzb()).a();
        b.C0705b a26 = b.a("onDeviceImageLabelCreateLogEvent");
        zzae zzaeVar15 = new zzae();
        zzaeVar15.zza(48);
        zzp = a26.b(zzaeVar15.zzb()).a();
        b.C0705b a27 = b.a("onDeviceImageLabelLoadLogEvent");
        zzae zzaeVar16 = new zzae();
        zzaeVar16.zza(49);
        zzq = a27.b(zzaeVar16.zzb()).a();
        b.C0705b a28 = b.a("onDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar17 = new zzae();
        zzaeVar17.zza(18);
        zzr = a28.b(zzaeVar17.zzb()).a();
        b.C0705b a29 = b.a("onDeviceObjectCreateLogEvent");
        zzae zzaeVar18 = new zzae();
        zzaeVar18.zza(26);
        zzs = a29.b(zzaeVar18.zzb()).a();
        b.C0705b a31 = b.a("onDeviceObjectLoadLogEvent");
        zzae zzaeVar19 = new zzae();
        zzaeVar19.zza(27);
        zzt = a31.b(zzaeVar19.zzb()).a();
        b.C0705b a32 = b.a("onDeviceObjectInferenceLogEvent");
        zzae zzaeVar20 = new zzae();
        zzaeVar20.zza(28);
        zzu = a32.b(zzaeVar20.zzb()).a();
        b.C0705b a33 = b.a("onDevicePoseDetectionLogEvent");
        zzae zzaeVar21 = new zzae();
        zzaeVar21.zza(44);
        zzv = a33.b(zzaeVar21.zzb()).a();
        b.C0705b a34 = b.a("onDeviceSegmentationLogEvent");
        zzae zzaeVar22 = new zzae();
        zzaeVar22.zza(45);
        zzw = a34.b(zzaeVar22.zzb()).a();
        b.C0705b a35 = b.a("onDeviceSmartReplyLogEvent");
        zzae zzaeVar23 = new zzae();
        zzaeVar23.zza(19);
        zzx = a35.b(zzaeVar23.zzb()).a();
        b.C0705b a36 = b.a("onDeviceLanguageIdentificationLogEvent");
        zzae zzaeVar24 = new zzae();
        zzaeVar24.zza(21);
        zzy = a36.b(zzaeVar24.zzb()).a();
        b.C0705b a37 = b.a("onDeviceTranslationLogEvent");
        zzae zzaeVar25 = new zzae();
        zzaeVar25.zza(22);
        zzz = a37.b(zzaeVar25.zzb()).a();
        b.C0705b a38 = b.a("cloudFaceDetectionLogEvent");
        zzae zzaeVar26 = new zzae();
        zzaeVar26.zza(8);
        zzA = a38.b(zzaeVar26.zzb()).a();
        b.C0705b a39 = b.a("cloudCropHintDetectionLogEvent");
        zzae zzaeVar27 = new zzae();
        zzaeVar27.zza(9);
        zzB = a39.b(zzaeVar27.zzb()).a();
        b.C0705b a41 = b.a("cloudDocumentTextDetectionLogEvent");
        zzae zzaeVar28 = new zzae();
        zzaeVar28.zza(10);
        zzC = a41.b(zzaeVar28.zzb()).a();
        b.C0705b a42 = b.a("cloudImagePropertiesDetectionLogEvent");
        zzae zzaeVar29 = new zzae();
        zzaeVar29.zza(11);
        zzD = a42.b(zzaeVar29.zzb()).a();
        b.C0705b a43 = b.a("cloudImageLabelDetectionLogEvent");
        zzae zzaeVar30 = new zzae();
        zzaeVar30.zza(12);
        zzE = a43.b(zzaeVar30.zzb()).a();
        b.C0705b a44 = b.a("cloudLandmarkDetectionLogEvent");
        zzae zzaeVar31 = new zzae();
        zzaeVar31.zza(13);
        zzF = a44.b(zzaeVar31.zzb()).a();
        b.C0705b a45 = b.a("cloudLogoDetectionLogEvent");
        zzae zzaeVar32 = new zzae();
        zzaeVar32.zza(14);
        zzG = a45.b(zzaeVar32.zzb()).a();
        b.C0705b a46 = b.a("cloudSafeSearchDetectionLogEvent");
        zzae zzaeVar33 = new zzae();
        zzaeVar33.zza(15);
        zzH = a46.b(zzaeVar33.zzb()).a();
        b.C0705b a47 = b.a("cloudTextDetectionLogEvent");
        zzae zzaeVar34 = new zzae();
        zzaeVar34.zza(16);
        zzI = a47.b(zzaeVar34.zzb()).a();
        b.C0705b a48 = b.a("cloudWebSearchDetectionLogEvent");
        zzae zzaeVar35 = new zzae();
        zzaeVar35.zza(17);
        zzJ = a48.b(zzaeVar35.zzb()).a();
        b.C0705b a49 = b.a("automlImageLabelingCreateLogEvent");
        zzae zzaeVar36 = new zzae();
        zzaeVar36.zza(23);
        zzK = a49.b(zzaeVar36.zzb()).a();
        b.C0705b a51 = b.a("automlImageLabelingLoadLogEvent");
        zzae zzaeVar37 = new zzae();
        zzaeVar37.zza(24);
        zzL = a51.b(zzaeVar37.zzb()).a();
        b.C0705b a52 = b.a("automlImageLabelingInferenceLogEvent");
        zzae zzaeVar38 = new zzae();
        zzaeVar38.zza(25);
        zzM = a52.b(zzaeVar38.zzb()).a();
        b.C0705b a53 = b.a("isModelDownloadedLogEvent");
        zzae zzaeVar39 = new zzae();
        zzaeVar39.zza(39);
        zzN = a53.b(zzaeVar39.zzb()).a();
        b.C0705b a54 = b.a("deleteModelLogEvent");
        zzae zzaeVar40 = new zzae();
        zzaeVar40.zza(40);
        zzO = a54.b(zzaeVar40.zzb()).a();
        b.C0705b a55 = b.a("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzae zzaeVar41 = new zzae();
        zzaeVar41.zza(30);
        zzP = a55.b(zzaeVar41.zzb()).a();
        b.C0705b a56 = b.a("aggregatedCustomModelInferenceLogEvent");
        zzae zzaeVar42 = new zzae();
        zzaeVar42.zza(31);
        zzQ = a56.b(zzaeVar42.zzb()).a();
        b.C0705b a57 = b.a("aggregatedOnDeviceFaceDetectionLogEvent");
        zzae zzaeVar43 = new zzae();
        zzaeVar43.zza(32);
        zzR = a57.b(zzaeVar43.zzb()).a();
        b.C0705b a58 = b.a("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzae zzaeVar44 = new zzae();
        zzaeVar44.zza(33);
        zzS = a58.b(zzaeVar44.zzb()).a();
        b.C0705b a59 = b.a("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzae zzaeVar45 = new zzae();
        zzaeVar45.zza(34);
        zzT = a59.b(zzaeVar45.zzb()).a();
        b.C0705b a61 = b.a("aggregatedOnDeviceObjectInferenceLogEvent");
        zzae zzaeVar46 = new zzae();
        zzaeVar46.zza(35);
        zzU = a61.b(zzaeVar46.zzb()).a();
        b.C0705b a62 = b.a("aggregatedOnDeviceTextDetectionLogEvent");
        zzae zzaeVar47 = new zzae();
        zzaeVar47.zza(36);
        zzV = a62.b(zzaeVar47.zzb()).a();
        b.C0705b a63 = b.a("aggregatedOnDevicePoseDetectionLogEvent");
        zzae zzaeVar48 = new zzae();
        zzaeVar48.zza(46);
        zzW = a63.b(zzaeVar48.zzb()).a();
        b.C0705b a64 = b.a("aggregatedOnDeviceSegmentationLogEvent");
        zzae zzaeVar49 = new zzae();
        zzaeVar49.zza(47);
        zzX = a64.b(zzaeVar49.zzb()).a();
        b.C0705b a65 = b.a("pipelineAccelerationInferenceEvents");
        zzae zzaeVar50 = new zzae();
        zzaeVar50.zza(69);
        zzY = a65.b(zzaeVar50.zzb()).a();
        b.C0705b a66 = b.a("remoteConfigLogEvent");
        zzae zzaeVar51 = new zzae();
        zzaeVar51.zza(42);
        zzZ = a66.b(zzaeVar51.zzb()).a();
        b.C0705b a67 = b.a("inputImageConstructionLogEvent");
        zzae zzaeVar52 = new zzae();
        zzaeVar52.zza(50);
        zzaa = a67.b(zzaeVar52.zzb()).a();
        b.C0705b a68 = b.a("leakedHandleEvent");
        zzae zzaeVar53 = new zzae();
        zzaeVar53.zza(51);
        zzab = a68.b(zzaeVar53.zzb()).a();
        b.C0705b a69 = b.a("cameraSourceLogEvent");
        zzae zzaeVar54 = new zzae();
        zzaeVar54.zza(52);
        zzac = a69.b(zzaeVar54.zzb()).a();
        b.C0705b a71 = b.a("imageLabelOptionalModuleLogEvent");
        zzae zzaeVar55 = new zzae();
        zzaeVar55.zza(53);
        zzad = a71.b(zzaeVar55.zzb()).a();
        b.C0705b a72 = b.a("languageIdentificationOptionalModuleLogEvent");
        zzae zzaeVar56 = new zzae();
        zzaeVar56.zza(54);
        zzae = a72.b(zzaeVar56.zzb()).a();
        b.C0705b a73 = b.a("faceDetectionOptionalModuleLogEvent");
        zzae zzaeVar57 = new zzae();
        zzaeVar57.zza(60);
        zzaf = a73.b(zzaeVar57.zzb()).a();
        b.C0705b a74 = b.a("nlClassifierOptionalModuleLogEvent");
        zzae zzaeVar58 = new zzae();
        zzaeVar58.zza(55);
        zzag = a74.b(zzaeVar58.zzb()).a();
        b.C0705b a75 = b.a("nlClassifierClientLibraryLogEvent");
        zzae zzaeVar59 = new zzae();
        zzaeVar59.zza(56);
        zzah = a75.b(zzaeVar59.zzb()).a();
        b.C0705b a76 = b.a("accelerationAllowlistLogEvent");
        zzae zzaeVar60 = new zzae();
        zzaeVar60.zza(57);
        zzai = a76.b(zzaeVar60.zzb()).a();
        b.C0705b a77 = b.a("toxicityDetectionCreateEvent");
        zzae zzaeVar61 = new zzae();
        zzaeVar61.zza(62);
        zzaj = a77.b(zzaeVar61.zzb()).a();
        b.C0705b a78 = b.a("toxicityDetectionLoadEvent");
        zzae zzaeVar62 = new zzae();
        zzaeVar62.zza(63);
        zzak = a78.b(zzaeVar62.zzb()).a();
        b.C0705b a79 = b.a("toxicityDetectionInferenceEvent");
        zzae zzaeVar63 = new zzae();
        zzaeVar63.zza(64);
        zzal = a79.b(zzaeVar63.zzb()).a();
        b.C0705b a81 = b.a("barcodeDetectionOptionalModuleLogEvent");
        zzae zzaeVar64 = new zzae();
        zzaeVar64.zza(65);
        zzam = a81.b(zzaeVar64.zzb()).a();
        b.C0705b a82 = b.a("customImageLabelOptionalModuleLogEvent");
        zzae zzaeVar65 = new zzae();
        zzaeVar65.zza(66);
        zzan = a82.b(zzaeVar65.zzb()).a();
        b.C0705b a83 = b.a("codeScannerScanApiEvent");
        zzae zzaeVar66 = new zzae();
        zzaeVar66.zza(67);
        zzao = a83.b(zzaeVar66.zzb()).a();
        b.C0705b a84 = b.a("codeScannerOptionalModuleEvent");
        zzae zzaeVar67 = new zzae();
        zzaeVar67.zza(68);
        zzap = a84.b(zzaeVar67.zzb()).a();
        b.C0705b a85 = b.a("onDeviceExplicitContentCreateLogEvent");
        zzae zzaeVar68 = new zzae();
        zzaeVar68.zza(70);
        zzaq = a85.b(zzaeVar68.zzb()).a();
        b.C0705b a86 = b.a("onDeviceExplicitContentLoadLogEvent");
        zzae zzaeVar69 = new zzae();
        zzaeVar69.zza(71);
        zzar = a86.b(zzaeVar69.zzb()).a();
        b.C0705b a87 = b.a("onDeviceExplicitContentInferenceLogEvent");
        zzae zzaeVar70 = new zzae();
        zzaeVar70.zza(72);
        zzas = a87.b(zzaeVar70.zzb()).a();
        b.C0705b a88 = b.a("aggregatedOnDeviceExplicitContentLogEvent");
        zzae zzaeVar71 = new zzae();
        zzaeVar71.zza(73);
        zzat = a88.b(zzaeVar71.zzb()).a();
        b.C0705b a89 = b.a("onDeviceFaceMeshCreateLogEvent");
        zzae zzaeVar72 = new zzae();
        zzaeVar72.zza(74);
        zzau = a89.b(zzaeVar72.zzb()).a();
        b.C0705b a90 = b.a("onDeviceFaceMeshLoadLogEvent");
        zzae zzaeVar73 = new zzae();
        zzaeVar73.zza(75);
        zzav = a90.b(zzaeVar73.zzb()).a();
        b.C0705b a91 = b.a("onDeviceFaceMeshLogEvent");
        zzae zzaeVar74 = new zzae();
        zzaeVar74.zza(76);
        zzaw = a91.b(zzaeVar74.zzb()).a();
        b.C0705b a92 = b.a("aggregatedOnDeviceFaceMeshLogEvent");
        zzae zzaeVar75 = new zzae();
        zzaeVar75.zza(77);
        zzax = a92.b(zzaeVar75.zzb()).a();
        b.C0705b a93 = b.a("smartReplyOptionalModuleLogEvent");
        zzae zzaeVar76 = new zzae();
        zzaeVar76.zza(78);
        zzay = a93.b(zzaeVar76.zzb()).a();
        b.C0705b a94 = b.a("textDetectionOptionalModuleLogEvent");
        zzae zzaeVar77 = new zzae();
        zzaeVar77.zza(80);
        zzaz = a94.b(zzaeVar77.zzb()).a();
    }

    private zzea() {
    }

    @Override // lm.c
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzhw zzhwVar = (zzhw) obj;
        d dVar = (d) obj2;
        dVar.add(zzb, zzhwVar.zzc());
        dVar.add(zzc, zzhwVar.zzb());
        dVar.add(zzd, (Object) null);
        dVar.add(zze, (Object) null);
        dVar.add(zzf, (Object) null);
        dVar.add(zzg, (Object) null);
        dVar.add(zzh, (Object) null);
        dVar.add(zzi, (Object) null);
        dVar.add(zzj, (Object) null);
        dVar.add(zzk, (Object) null);
        dVar.add(zzl, (Object) null);
        dVar.add(zzm, (Object) null);
        dVar.add(zzn, (Object) null);
        dVar.add(zzo, (Object) null);
        dVar.add(zzp, (Object) null);
        dVar.add(zzq, (Object) null);
        dVar.add(zzr, (Object) null);
        dVar.add(zzs, (Object) null);
        dVar.add(zzt, (Object) null);
        dVar.add(zzu, (Object) null);
        dVar.add(zzv, (Object) null);
        dVar.add(zzw, (Object) null);
        dVar.add(zzx, (Object) null);
        dVar.add(zzy, (Object) null);
        dVar.add(zzz, (Object) null);
        dVar.add(zzA, (Object) null);
        dVar.add(zzB, (Object) null);
        dVar.add(zzC, (Object) null);
        dVar.add(zzD, (Object) null);
        dVar.add(zzE, (Object) null);
        dVar.add(zzF, (Object) null);
        dVar.add(zzG, (Object) null);
        dVar.add(zzH, (Object) null);
        dVar.add(zzI, (Object) null);
        dVar.add(zzJ, (Object) null);
        dVar.add(zzK, (Object) null);
        dVar.add(zzL, (Object) null);
        dVar.add(zzM, (Object) null);
        dVar.add(zzN, (Object) null);
        dVar.add(zzO, (Object) null);
        dVar.add(zzP, (Object) null);
        dVar.add(zzQ, (Object) null);
        dVar.add(zzR, (Object) null);
        dVar.add(zzS, (Object) null);
        dVar.add(zzT, (Object) null);
        dVar.add(zzU, (Object) null);
        dVar.add(zzV, (Object) null);
        dVar.add(zzW, (Object) null);
        dVar.add(zzX, (Object) null);
        dVar.add(zzY, (Object) null);
        dVar.add(zzZ, (Object) null);
        dVar.add(zzaa, zzhwVar.zza());
        dVar.add(zzab, (Object) null);
        dVar.add(zzac, (Object) null);
        dVar.add(zzad, (Object) null);
        dVar.add(zzae, (Object) null);
        dVar.add(zzaf, (Object) null);
        dVar.add(zzag, (Object) null);
        dVar.add(zzah, (Object) null);
        dVar.add(zzai, (Object) null);
        dVar.add(zzaj, (Object) null);
        dVar.add(zzak, (Object) null);
        dVar.add(zzal, (Object) null);
        dVar.add(zzam, (Object) null);
        dVar.add(zzan, (Object) null);
        dVar.add(zzao, (Object) null);
        dVar.add(zzap, (Object) null);
        dVar.add(zzaq, (Object) null);
        dVar.add(zzar, (Object) null);
        dVar.add(zzas, (Object) null);
        dVar.add(zzat, (Object) null);
        dVar.add(zzau, (Object) null);
        dVar.add(zzav, (Object) null);
        dVar.add(zzaw, (Object) null);
        dVar.add(zzax, (Object) null);
        dVar.add(zzay, (Object) null);
        dVar.add(zzaz, (Object) null);
    }
}