package com.google.android.gms.internal.mlkit_common;

import mm.a;
import mm.b;

/* loaded from: classes3.dex */
public final class zzhk implements a {
    public static final a zza = new zzhk();

    private zzhk() {
    }

    @Override // mm.a
    public final void configure(b bVar) {
        bVar.mo185registerEncoder(zzjc.class, zzfd.zza);
        bVar.mo185registerEncoder(zzlg.class, zzhc.zza);
        bVar.mo185registerEncoder(zzjg.class, zzfe.zza);
        bVar.mo185registerEncoder(zzjp.class, zzfg.zza);
        bVar.mo185registerEncoder(zzjl.class, zzff.zza);
        bVar.mo185registerEncoder(zzjn.class, zzfh.zza);
        bVar.mo185registerEncoder(zzie.class, zzem.zza);
        bVar.mo185registerEncoder(zzid.class, zzel.zza);
        bVar.mo185registerEncoder(zzin.class, zzew.zza);
        bVar.mo185registerEncoder(zzla.class, zzgu.zza);
        bVar.mo185registerEncoder(zzic.class, zzek.zza);
        bVar.mo185registerEncoder(zzib.class, zzej.zza);
        bVar.mo185registerEncoder(zzjy.class, zzfs.zza);
        bVar.mo185registerEncoder(zzly.class, zzes.zza);
        bVar.mo185registerEncoder(zzil.class, zzeu.zza);
        bVar.mo185registerEncoder(zzik.class, zzer.zza);
        bVar.mo185registerEncoder(zzjz.class, zzft.zza);
        bVar.mo185registerEncoder(zzkx.class, zzgr.zza);
        bVar.mo185registerEncoder(zzky.class, zzgs.zza);
        bVar.mo185registerEncoder(zzkw.class, zzgq.zza);
        bVar.mo185registerEncoder(zzjt.class, zzfn.zza);
        bVar.mo185registerEncoder(zzlx.class, zzdt.zza);
        bVar.mo185registerEncoder(zzju.class, zzfo.zza);
        bVar.mo185registerEncoder(zzka.class, zzfu.zza);
        bVar.mo185registerEncoder(zzkd.class, zzfx.zza);
        bVar.mo185registerEncoder(zzkc.class, zzfw.zza);
        bVar.mo185registerEncoder(zzkb.class, zzfv.zza);
        bVar.mo185registerEncoder(zzki.class, zzgc.zza);
        bVar.mo185registerEncoder(zzkj.class, zzgd.zza);
        bVar.mo185registerEncoder(zzkl.class, zzgf.zza);
        bVar.mo185registerEncoder(zzkk.class, zzge.zza);
        bVar.mo185registerEncoder(zzjs.class, zzfm.zza);
        bVar.mo185registerEncoder(zzkm.class, zzgg.zza);
        bVar.mo185registerEncoder(zzkn.class, zzgh.zza);
        bVar.mo185registerEncoder(zzko.class, zzgi.zza);
        bVar.mo185registerEncoder(zzkp.class, zzgj.zza);
        bVar.mo185registerEncoder(zzkv.class, zzgo.zza);
        bVar.mo185registerEncoder(zzku.class, zzgp.zza);
        bVar.mo185registerEncoder(zzkh.class, zzfy.zza);
        bVar.mo185registerEncoder(zzit.class, zzfb.zza);
        bVar.mo185registerEncoder(zzkf.class, zzga.zza);
        bVar.mo185registerEncoder(zzke.class, zzfz.zza);
        bVar.mo185registerEncoder(zzkg.class, zzgb.zza);
        bVar.mo185registerEncoder(zzkz.class, zzgt.zza);
        bVar.mo185registerEncoder(zzlk.class, zzhg.zza);
        bVar.mo185registerEncoder(zzhq.class, zzdy.zza);
        bVar.mo185registerEncoder(zzho.class, zzdw.zza);
        bVar.mo185registerEncoder(zzhn.class, zzdv.zza);
        bVar.mo185registerEncoder(zzhp.class, zzdx.zza);
        bVar.mo185registerEncoder(zzhs.class, zzea.zza);
        bVar.mo185registerEncoder(zzhr.class, zzdz.zza);
        bVar.mo185registerEncoder(zzht.class, zzeb.zza);
        bVar.mo185registerEncoder(zzhu.class, zzec.zza);
        bVar.mo185registerEncoder(zzhv.class, zzed.zza);
        bVar.mo185registerEncoder(zzhw.class, zzee.zza);
        bVar.mo185registerEncoder(zzhx.class, zzef.zza);
        bVar.mo185registerEncoder(zzcp.class, zzdp.zza);
        bVar.mo185registerEncoder(zzcr.class, zzdr.zza);
        bVar.mo185registerEncoder(zzcq.class, zzdq.zza);
        bVar.mo185registerEncoder(zzir.class, zzez.zza);
        bVar.mo185registerEncoder(zzih.class, zzen.zza);
        bVar.mo185registerEncoder(zzbu.class, zzct.zza);
        bVar.mo185registerEncoder(zzbt.class, zzcu.zza);
        bVar.mo185registerEncoder(zzii.class, zzep.zza);
        bVar.mo185registerEncoder(zzbw.class, zzcv.zza);
        bVar.mo185registerEncoder(zzbv.class, zzcw.zza);
        bVar.mo185registerEncoder(zzcc.class, zzdb.zza);
        bVar.mo185registerEncoder(zzcb.class, zzdc.zza);
        bVar.mo185registerEncoder(zzby.class, zzcx.zza);
        bVar.mo185registerEncoder(zzbx.class, zzcy.zza);
        bVar.mo185registerEncoder(zzce.class, zzdd.zza);
        bVar.mo185registerEncoder(zzcd.class, zzde.zza);
        bVar.mo185registerEncoder(zzcg.class, zzdf.zza);
        bVar.mo185registerEncoder(zzcf.class, zzdg.zza);
        bVar.mo185registerEncoder(zzco.class, zzdn.zza);
        bVar.mo185registerEncoder(zzcn.class, zzdo.zza);
        bVar.mo185registerEncoder(zzci.class, zzdh.zza);
        bVar.mo185registerEncoder(zzch.class, zzdi.zza);
        bVar.mo185registerEncoder(zzck.class, zzdj.zza);
        bVar.mo185registerEncoder(zzcj.class, zzdk.zza);
        bVar.mo185registerEncoder(zzls.class, zzgx.zza);
        bVar.mo185registerEncoder(zzll.class, zzeo.zza);
        bVar.mo185registerEncoder(zzlp.class, zzfl.zza);
        bVar.mo185registerEncoder(zzlo.class, zzfk.zza);
        bVar.mo185registerEncoder(zzlm.class, zzet.zza);
        bVar.mo185registerEncoder(zzlr.class, zzgw.zza);
        bVar.mo185registerEncoder(zzlq.class, zzgv.zza);
        bVar.mo185registerEncoder(zzlt.class, zzgy.zza);
        bVar.mo185registerEncoder(zzln.class, zzex.zza);
        bVar.mo185registerEncoder(zzlw.class, zzhi.zza);
        bVar.mo185registerEncoder(zzlv.class, zzhj.zza);
        bVar.mo185registerEncoder(zzlu.class, zzhh.zza);
        bVar.mo185registerEncoder(zzlb.class, zzgz.zza);
        bVar.mo185registerEncoder(zzio.class, zzey.zza);
        bVar.mo185registerEncoder(zzix.class, zzfc.zza);
        bVar.mo185registerEncoder(zzhm.class, zzdu.zza);
        bVar.mo185registerEncoder(zzim.class, zzev.zza);
        bVar.mo185registerEncoder(zzis.class, zzfa.zza);
        bVar.mo185registerEncoder(zzij.class, zzeq.zza);
        bVar.mo185registerEncoder(zzjr.class, zzfj.zza);
        bVar.mo185registerEncoder(zzjq.class, zzfi.zza);
        bVar.mo185registerEncoder(zzbs.class, zzcs.zza);
        bVar.mo185registerEncoder(zzlh.class, zzhd.zza);
        bVar.mo185registerEncoder(zzlj.class, zzhf.zza);
        bVar.mo185registerEncoder(zzli.class, zzhe.zza);
        bVar.mo185registerEncoder(zzhl.class, zzds.zza);
        bVar.mo185registerEncoder(zzia.class, zzei.zza);
        bVar.mo185registerEncoder(zzhz.class, zzeh.zza);
        bVar.mo185registerEncoder(zzhy.class, zzeg.zza);
        bVar.mo185registerEncoder(zzjv.class, zzfp.zza);
        bVar.mo185registerEncoder(zzjx.class, zzfr.zza);
        bVar.mo185registerEncoder(zzjw.class, zzfq.zza);
        bVar.mo185registerEncoder(zzca.class, zzcz.zza);
        bVar.mo185registerEncoder(zzbz.class, zzda.zza);
        bVar.mo185registerEncoder(zzkq.class, zzgk.zza);
        bVar.mo185registerEncoder(zzkt.class, zzgn.zza);
        bVar.mo185registerEncoder(zzkr.class, zzgl.zza);
        bVar.mo185registerEncoder(zzks.class, zzgm.zza);
        bVar.mo185registerEncoder(zzcm.class, zzdl.zza);
        bVar.mo185registerEncoder(zzcl.class, zzdm.zza);
        bVar.mo185registerEncoder(zzld.class, zzhb.zza);
        bVar.mo185registerEncoder(zzlc.class, zzha.zza);
    }
}